[global]
address = "0.0.0.0"
port = 80

[development]
address = "0.0.0.0"
port = 80
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 80

[production]
address = "0.0.0.0"
port = 80