name: Rust

on:
  push:
    branches: [ "new" ]
  pull_request:
    branches: [ "new" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: rust-build/rust-build.action@v1.4.3
      env:
          TOOLCHAIN_VERSION: nightly-x86_64-unknown-linux-gnu
      # run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose
